# Travis-CI: https://travis-ci.org/kapsiry/sikteeri
language: python
cache: pip
python:
  - "2.7"
before_install:
 - "sudo locale-gen fi_FI.UTF-8"
 - "pip install pytest-coverage pytest-django"
script: "./test.sh"
sudo: true
